import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'

// ─── Role-based notification type definitions ────────────────────────────────
// Each role gets notifications relevant to their workflow

const STUDENT_NOTIFICATIONS = (userId: string, now: Date) => [
  {
    userId,
    type: 'enrollment',
    title: 'Welcome to ShijlAI Academy! 🎉',
    content: 'Your account has been created successfully. Start exploring courses and begin your learning journey!',
    icon: '🎓',
    priority: 'high',
    category: 'system',
    actionLabel: 'Explore Courses',
    actionUrl: '/courses',
    isRead: false,
  },
  {
    userId,
    type: 'achievement',
    title: 'First Login Badge Earned! ⭐',
    content: 'Congratulations! You\'ve earned the "First Login" badge. Keep going to unlock more achievements!',
    icon: '🏆',
    priority: 'normal',
    category: 'academic',
    actionLabel: 'View Badges',
    actionUrl: '/achievements',
    isRead: false,
  },
  {
    userId,
    type: 'course_update',
    title: 'New Lesson Available: Introduction to AI',
    content: 'A new lesson "Introduction to Artificial Intelligence" has been added to Python for Data Science.',
    icon: '📚',
    priority: 'normal',
    category: 'academic',
    actionLabel: 'Go to Lesson',
    actionUrl: '/courses',
    isRead: false,
    createdAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'assignment',
    title: 'Assignment Due Tomorrow',
    content: 'Your "Data Structures Implementation" assignment is due tomorrow at 11:59 PM. Don\'t forget to submit!',
    icon: '📝',
    priority: 'urgent',
    category: 'academic',
    actionLabel: 'View Assignment',
    actionUrl: '/student-assignments',
    dismissLabel: 'Remind Later',
    isRead: false,
    expiresAt: new Date(now.getTime() + 36 * 60 * 60 * 1000),
    createdAt: new Date(now.getTime() - 5 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'qa',
    title: 'Your Question Has Been Answered',
    content: 'Ahmed Khan answered your question "How does recursion work in Python?" in Python for Data Science.',
    icon: '💬',
    priority: 'normal',
    category: 'social',
    actionLabel: 'View Answer',
    actionUrl: '/student-qa',
    isRead: false,
    createdAt: new Date(now.getTime() - 8 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'review',
    title: 'Course Review Request',
    content: 'You recently completed "Web Development Fundamentals". Share your experience to help other learners!',
    icon: '⭐',
    priority: 'normal',
    category: 'social',
    actionLabel: 'Write Review',
    actionUrl: '/courses',
    dismissLabel: 'Maybe Later',
    isRead: true,
    readAt: new Date(now.getTime() - 1 * 60 * 60 * 1000),
    createdAt: new Date(now.getTime() - 24 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'live_session',
    title: 'Live Session Starting in 30 Minutes',
    content: 'Dr. Sara Malik\'s live Q&A session "Advanced Python Tips" starts at 3:00 PM PKT today.',
    icon: '🔴',
    priority: 'urgent',
    category: 'academic',
    actionLabel: 'Join Session',
    actionUrl: '/student-schedule',
    isRead: false,
    expiresAt: new Date(now.getTime() - 20 * 60 * 60 * 1000),
    createdAt: new Date(now.getTime() - 26 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'security',
    title: 'New Login from Chrome on Windows',
    content: 'A new login to your account was detected from Chrome on Windows at 103.45.67.89. If this wasn\'t you, please secure your account.',
    icon: '🔒',
    priority: 'high',
    category: 'security',
    actionLabel: 'Review Activity',
    actionUrl: '/settings',
    dismissLabel: 'It was me',
    isRead: false,
    createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'reminder',
    title: 'Continue Your Learning Streak!',
    content: 'You\'re on a 7-day streak! Complete a lesson today to keep it going. Streaks help you learn consistently.',
    icon: '🔥',
    priority: 'high',
    category: 'academic',
    actionLabel: 'Continue Learning',
    actionUrl: '/courses',
    isPinned: true,
    pinnedAt: new Date(now.getTime() - 4 * 60 * 60 * 1000),
    isRead: false,
    createdAt: new Date(now.getTime() - 4 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'promotion',
    title: '🎉 30% Off All Pro Courses This Week!',
    content: 'Limited time offer: Get 30% off on all Pro courses. Use code LEARN30 at checkout. Offer ends Sunday!',
    icon: '🎁',
    priority: 'normal',
    category: 'general',
    actionLabel: 'Browse Courses',
    actionUrl: '/courses',
    dismissLabel: 'Not Interested',
    isRead: true,
    readAt: new Date(now.getTime() - 36 * 60 * 60 * 1000),
    createdAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'system',
    title: 'Platform Maintenance Scheduled',
    content: 'ShijlAI Academy will undergo scheduled maintenance on Saturday 2:00 AM - 4:00 AM PKT. Some features may be temporarily unavailable.',
    icon: '🔧',
    priority: 'normal',
    category: 'system',
    isArchived: true,
    archivedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000),
    isRead: true,
    readAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000),
    createdAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000),
  },
]

const INSTRUCTOR_NOTIFICATIONS = (userId: string, now: Date) => [
  {
    userId,
    type: 'enrollment',
    title: 'Welcome to ShijlAI Academy! 🎉',
    content: 'Your instructor account has been set up successfully. Start creating courses and sharing your knowledge!',
    icon: '🎓',
    priority: 'high',
    category: 'system',
    actionLabel: 'Create Course',
    actionUrl: '/instructor-courses',
    isRead: false,
  },
  {
    userId,
    type: 'achievement',
    title: 'Instructor Badge Earned! ⭐',
    content: 'Congratulations! You\'ve earned the "Instructor" badge. Welcome to the teaching community!',
    icon: '🏆',
    priority: 'normal',
    category: 'academic',
    actionLabel: 'View Profile',
    actionUrl: '/instructor-profile',
    isRead: false,
  },
  {
    userId,
    type: 'social',
    title: 'Bilal Raza enrolled in your course',
    content: 'Bilal Raza just enrolled in "Advanced React Patterns". Your course is growing!',
    icon: '👤',
    priority: 'normal',
    category: 'social',
    isRead: true,
    readAt: new Date(now.getTime() - 18 * 60 * 60 * 1000),
    createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'social',
    title: 'Fatima Khan enrolled in your course',
    content: 'Fatima Khan just enrolled in "Python for Data Science". You now have 50+ students!',
    icon: '👤',
    priority: 'normal',
    category: 'social',
    actionLabel: 'View Students',
    actionUrl: '/instructor-students',
    isRead: false,
    createdAt: new Date(now.getTime() - 6 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'payout',
    title: 'Payout of $125 Processed',
    content: 'Your monthly payout of $125 has been processed via bank transfer. It should arrive within 2-3 business days.',
    icon: '💰',
    priority: 'high',
    category: 'financial',
    actionLabel: 'View Details',
    actionUrl: '/instructor-revenue',
    isRead: true,
    readAt: new Date(now.getTime() - 12 * 60 * 60 * 1000),
    createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'payout',
    title: 'Monthly Earnings Report Ready',
    content: 'Your earnings report for this month is ready. You earned $452 with 3 active courses.',
    icon: '📊',
    priority: 'high',
    category: 'financial',
    actionLabel: 'View Report',
    actionUrl: '/instructor-revenue',
    isRead: false,
    createdAt: new Date(now.getTime() - 3 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'review',
    title: 'New 5-Star Review on Your Course!',
    content: 'A student left a glowing review on "Advanced React Patterns": "Best course on React I\'ve ever taken!"',
    icon: '⭐',
    priority: 'normal',
    category: 'social',
    actionLabel: 'View Review',
    actionUrl: '/instructor-reviews',
    isRead: false,
    createdAt: new Date(now.getTime() - 10 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'course_update',
    title: 'Course Approval: Python for Data Science',
    content: 'Your course "Python for Data Science" has been approved and is now live on the platform!',
    icon: '✅',
    priority: 'high',
    category: 'academic',
    actionLabel: 'View Course',
    actionUrl: '/instructor-courses',
    isRead: true,
    readAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
    createdAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'qa',
    title: 'New Question in Your Course',
    content: 'Ahmed Ali asked a question in "Advanced React Patterns": "How do hooks work with TypeScript?"',
    icon: '💬',
    priority: 'normal',
    category: 'social',
    actionLabel: 'Answer Question',
    actionUrl: '/instructor-qa',
    isRead: false,
    createdAt: new Date(now.getTime() - 4 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'reminder',
    title: 'Complete Your Course Setup',
    content: 'Your draft course "Machine Learning Basics" is 80% complete. Add the remaining modules to publish it!',
    icon: '📝',
    priority: 'high',
    category: 'academic',
    actionLabel: 'Edit Course',
    actionUrl: '/instructor-courses',
    isPinned: true,
    pinnedAt: new Date(now.getTime() - 1 * 60 * 60 * 1000),
    isRead: false,
    createdAt: new Date(now.getTime() - 1 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'live_session',
    title: 'Upcoming Live Session Reminder',
    content: 'Your scheduled live session "React Q&A" is tomorrow at 4:00 PM PKT. Don\'t forget to prepare!',
    icon: '🔴',
    priority: 'high',
    category: 'academic',
    actionLabel: 'View Schedule',
    actionUrl: '/instructor-schedule',
    isRead: false,
    createdAt: new Date(now.getTime() - 8 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'security',
    title: 'New Login from Chrome on Windows',
    content: 'A new login to your account was detected from Chrome on Windows at 103.45.67.89. If this wasn\'t you, please secure your account.',
    icon: '🔒',
    priority: 'high',
    category: 'security',
    actionLabel: 'Review Activity',
    actionUrl: '/settings',
    dismissLabel: 'It was me',
    isRead: false,
    createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'promotion',
    title: '🎉 Instructor Promotion: 0% Platform Fee This Month!',
    content: 'Special offer for active instructors: Enjoy 0% platform fee on all new course sales this month. Start publishing!',
    icon: '🎁',
    priority: 'normal',
    category: 'general',
    actionLabel: 'Learn More',
    actionUrl: '/instructor-courses',
    dismissLabel: 'Not Interested',
    isRead: true,
    readAt: new Date(now.getTime() - 36 * 60 * 60 * 1000),
    createdAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'system',
    title: 'Platform Maintenance Scheduled',
    content: 'ShijlAI Academy will undergo scheduled maintenance on Saturday 2:00 AM - 4:00 AM PKT. Some features may be temporarily unavailable.',
    icon: '🔧',
    priority: 'normal',
    category: 'system',
    isArchived: true,
    archivedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000),
    isRead: true,
    readAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000),
    createdAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000),
  },
]

const ADMIN_NOTIFICATIONS = (userId: string, now: Date) => [
  {
    userId,
    type: 'enrollment',
    title: 'Welcome to Admin Portal! 🛡️',
    content: 'Your admin account is ready. Manage users, courses, and platform settings from the dashboard.',
    icon: '🛡️',
    priority: 'high',
    category: 'system',
    actionLabel: 'Go to Dashboard',
    actionUrl: '/admin',
    isRead: false,
  },
  {
    userId,
    type: 'system',
    title: 'New Instructor Application Received',
    content: 'Dr. Ahmed Khan has submitted an instructor application. Review their credentials and approve or reject.',
    icon: '📋',
    priority: 'high',
    category: 'system',
    actionLabel: 'Review Application',
    actionUrl: '/admin-instructors',
    isRead: false,
    createdAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'system',
    title: 'Course Flagged for Review',
    content: 'The course "Advanced Hacking Techniques" has been flagged by 3 users. Immediate review required.',
    icon: '🚩',
    priority: 'urgent',
    category: 'system',
    actionLabel: 'Review Course',
    actionUrl: '/admin-courses',
    isRead: false,
    createdAt: new Date(now.getTime() - 5 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'payout',
    title: 'Payout Summary: $2,850 Pending',
    content: '12 instructor payout requests totaling $2,850 are pending approval for this cycle.',
    icon: '💰',
    priority: 'high',
    category: 'financial',
    actionLabel: 'Review Payouts',
    actionUrl: '/admin-payouts',
    isRead: false,
    createdAt: new Date(now.getTime() - 8 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'security',
    title: 'Suspicious Login Activity Detected',
    content: 'Multiple failed login attempts from IP 192.168.45.12. Consider blocking this IP address.',
    icon: '🔒',
    priority: 'urgent',
    category: 'security',
    actionLabel: 'View Details',
    actionUrl: '/admin-security',
    isRead: false,
    createdAt: new Date(now.getTime() - 3 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'system',
    title: 'Platform Maintenance Scheduled',
    content: 'ShijlAI Academy will undergo scheduled maintenance on Saturday 2:00 AM - 4:00 AM PKT.',
    icon: '🔧',
    priority: 'normal',
    category: 'system',
    isRead: true,
    readAt: new Date(now.getTime() - 6 * 60 * 60 * 1000),
    createdAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'reminder',
    title: 'Monthly Revenue Report Ready',
    content: 'The monthly revenue report for this month is ready. Total revenue: $12,500.',
    icon: '📊',
    priority: 'high',
    category: 'financial',
    actionLabel: 'View Report',
    actionUrl: '/admin-revenue',
    isRead: false,
    createdAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'security',
    title: 'New Login from Chrome on Windows',
    content: 'A new login to your admin account was detected from Chrome on Windows at 103.45.67.89.',
    icon: '🔒',
    priority: 'high',
    category: 'security',
    actionLabel: 'Review Activity',
    actionUrl: '/admin-security',
    dismissLabel: 'It was me',
    isRead: false,
    createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
  },
]

const PARENT_NOTIFICATIONS = (userId: string, now: Date) => [
  {
    userId,
    type: 'enrollment',
    title: 'Welcome to ShijlAI Academy! 👨‍👩‍👧',
    content: 'Your parent account has been created. Monitor your child\'s learning progress and stay informed!',
    icon: '👨‍👩‍👧',
    priority: 'high',
    category: 'system',
    actionLabel: 'View Dashboard',
    actionUrl: '/parent-dashboard',
    isRead: false,
  },
  {
    userId,
    type: 'achievement',
    title: 'Your Child Earned a Badge! ⭐',
    content: 'Congratulations! Your child earned the "Fast Learner" badge in Python for Data Science.',
    icon: '🏆',
    priority: 'normal',
    category: 'academic',
    actionLabel: 'View Progress',
    actionUrl: '/parent-progress',
    isRead: false,
  },
  {
    userId,
    type: 'reminder',
    title: 'Weekly Progress Report Available',
    content: 'Your child\'s weekly learning report is ready. They completed 3 lessons and scored 85% on quizzes.',
    icon: '📊',
    priority: 'high',
    category: 'academic',
    actionLabel: 'View Report',
    actionUrl: '/parent-reports',
    isRead: false,
    createdAt: new Date(now.getTime() - 4 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'course_update',
    title: 'New Course Recommendation',
    content: 'Based on your child\'s interests, we recommend "Web Development Fundamentals" — a great next step!',
    icon: '📚',
    priority: 'normal',
    category: 'academic',
    actionLabel: 'View Course',
    actionUrl: '/courses',
    isRead: false,
    createdAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'security',
    title: 'New Login Detected',
    content: 'A new login to your account was detected. If this wasn\'t you, please secure your account.',
    icon: '🔒',
    priority: 'high',
    category: 'security',
    actionLabel: 'Review Activity',
    actionUrl: '/settings',
    isRead: false,
    createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    userId,
    type: 'system',
    title: 'Platform Maintenance Scheduled',
    content: 'ShijlAI Academy will undergo scheduled maintenance on Saturday 2:00 AM - 4:00 AM PKT.',
    icon: '🔧',
    priority: 'normal',
    category: 'system',
    isRead: true,
    readAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000),
    createdAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000),
  },
]

// POST /api/notifications/seed — Seed role-appropriate notifications for the current user
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const userId = body.userId
    if (!userId) {
      return NextResponse.json({ error: 'userId is required' }, { status: 400 })
    }

    // Check if user already has notifications
    const existing = await db.notification.count({ where: { userId } })
    if (existing > 5) {
      return NextResponse.json({ success: true, message: 'User already has notifications', count: existing })
    }

    // Fetch user role to determine which notifications to create
    const userRecord = await db.user.findUnique({ where: { id: userId }, select: { role: true } })
    const userRole = userRecord?.role || 'student'

    const now = new Date()

    // Select notifications based on role
    let notifications: any[]
    switch (userRole) {
      case 'instructor':
        notifications = INSTRUCTOR_NOTIFICATIONS(userId, now)
        break
      case 'admin':
        notifications = ADMIN_NOTIFICATIONS(userId, now)
        break
      case 'parent':
        notifications = PARENT_NOTIFICATIONS(userId, now)
        break
      default:
        notifications = STUDENT_NOTIFICATIONS(userId, now)
        break
    }

    // Only pass fields that exist in the model
    const data = notifications.map(({ createdAt: ct, ...rest }) => ({
      ...rest,
      createdAt: ct || now,
    })) as any[]

    const result = await db.notification.createMany({ data })
    return NextResponse.json({ success: true, count: result.count, role: userRole })
  } catch (error) {
    console.error('[NOTIFICATIONS_SEED]', error)
    return NextResponse.json({ error: 'Failed to seed notifications' }, { status: 500 })
  }
}
